<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="MSTest" Version="4.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpAV1\SharpAV1.csproj" />
    <ProjectReference Include="..\SharpAV2\SharpAV2.csproj" />
    <ProjectReference Include="..\SharpH264\SharpH264.csproj" />
    <ProjectReference Include="..\SharpH265\SharpH265.csproj" />
    <ProjectReference Include="..\SharpH266\SharpH266.csproj" />
    <ProjectReference Include="..\SharpISOBMFF\SharpISOBMFF.csproj" />
    <ProjectReference Include="..\SharpMP4\SharpMP4.csproj" />
    <ProjectReference Include="..\SharpVP9\SharpVP9.csproj" />
    <ProjectReference Include="..\SharpH261\SharpH261.csproj" />
    <ProjectReference Include="..\SharpProRes\SharpProRes.csproj" />
    <ProjectReference Include="..\SharpH262\SharpH262.csproj" />
    <ProjectReference Include="..\SharpH263\SharpH263.csproj" />
    <ProjectReference Include="..\SharpMPEG4\SharpMPEG4.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Include="TestData\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
